on:
  push:
    paths-ignore:
      - README.md

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Sync Files
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.KEY }}
      run: |
        printf '%s' "$KEY" > id_rsa
        chmod 400 id_rsa
        rsync --exclude '.git' --delete -av -e "ssh -p $PORT -i id_rsa -o StrictHostKeyChecking=no" --rsync-path 'sudo rsync' --port=$PORT ./ $USERNAME@$HOST:/var/www/html/lottie-color-edit
        rm -f id_rsa
